### ISSUE TITLE
Configurable line endings

### ISSUE THREAD

**Issue by kmicklas** [cessen/ropey#43] opened 2021-07-30 23:57 UTC
I'm using Ropey for a LSP language server, which it seems was one of the motivating use cases for UTF-16 code unit indexing. One slight complication I noticed is that [LSP mandates that only `\n` and `\r\n`](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocuments) be treated as line endings while Ropey uses a [more general set of Unicode line boundary characters](https://docs.rs/ropey/1.3.1/ropey/#a-note-about-line-endings).

I think I can work around this by just replacing the alternate line breaks that Ropey recognizes with dummy whitespace characters if I receive them from the LSP client, so line indexing will stay coherent. But it would be nice if there was a native way to configure this so no workaround was required. This strategy isn't really ideal since the internal buffer doesn't necessarily match the file and correctly implementing certain features might require extra tracking of where to replace the dummy characters with the original values when sending text back to the client.

It looks like the set of newline characters Ropey recognizes is hard-coded, so maybe there isn't an API-compatible way to implement this without sacrificing non-negligible performance. If so, feel free to close this.

**Comment by cessen** [comment] 2021-07-31 01:56
Oh, that's unfortunate.  I'll look into it, but I'm not sure if I can add support in a sane way without adding parameters to existing functions/methods, which would break API compatibility.  I think the internal implementation wouldn't be too hard, though, and likely wouldn't be a significant performance hit if approached in the right way.

(As an aside: I guess this is one of the down sides to trying to be Unicode-conformant: when other people aren't, and those projects end up being popular, you end up as the odd one out, ha ha.)

Having said all of that, in practice I don't think it should be an issue?  Their mandate to only recognize `\n` and `\r\n` kind of defacto means that they don't accept *documents* with other line endings, because LSP would be interpreting them incorrectly.  And in practice, documents with line endings other than those two are extremely rare these days anyway.  So you could just report an error instead, as "unsupported document" or something like that.

Another possibility, depending on how LSP allows you to operate, is to just not operate in terms of line endings at all.  Just work with the text as a string of `char`s or bytes instead, and completely ignore Ropey's line-oriented APIs.  Ideally I would think it would be client's responsibility to translate char/byte/utf-16 offsets to line-column for the user if/when needed anyway.  But I'm not sure if LSP actually allows working that way.

**Comment by cessen** [comment] 2021-07-31 07:30
Looking into the spec, it seems that LSP *always* specifies text offsets as `line_number + utf16_offset`.  There's no option to specify using a plain offset from the beginning of the text.  That's unfortunate for a variety of reasons, one of which is precisely that it forced them to care about line endings, which in turn forces all clients and servers to adhere to the same line ending restrictions as the protocol. ~ *sigh* ~

In any case, I still would like to try to support this somehow, but I'm not 100% sure how best to approach it yet.  I'll leave this issue open for now.

In the mean time, I'd say just scan your documents for non-conforming line endings on load, and report an error in such cases.  The error will very likely never trigger in practice, and it keeps things from working incorrectly in the rare event that a non-conforming document is encountered.

**Comment by cessen** [comment] 2022-02-14 03:31
Duplicate of the newer (and more concrete) #53

**Closed by cessen** 2022-02-14 03:31 UTC
Labels: enhancement
